/**
 * /sitemap.txt — plain-text URL list for crawlers that prefer text over XML.
 *
 * The canonical sitemap is /sitemap-index.xml (generated by @astrojs/sitemap).
 * This is a complementary one-URL-per-line dump for the simpler crawlers
 * (some smaller AI ingestion bots, certain SEO audits) that don't follow
 * sitemap-index → sitemap-0.xml indirection.
 */
import { getCollection } from "astro:content";
import type { APIRoute } from "astro";
import { entryUrl, sectionUrl } from "~/lib/jsonld";
import { bare } from "~/lib/slug";
import { publicOnly } from "~/lib/visibility";

export const GET: APIRoute = async ({ site }) => {
  if (!site) {
    throw new Error("Astro.site must be set in astro.config.mjs");
  }

  const [dishes, recipes, farms, restaurants, garden, meals] = await Promise.all([
    getCollection("dishes").then(publicOnly),
    getCollection("recipes").then(publicOnly),
    getCollection("farms").then(publicOnly),
    getCollection("restaurants").then(publicOnly),
    getCollection("garden").then(publicOnly),
    getCollection("meals").then(publicOnly),
  ]);

  const urls: string[] = [
    site.toString(),
    new URL("/about/", site).toString(),
    sectionUrl(site, "dishes"),
    sectionUrl(site, "recipes"),
    sectionUrl(site, "restaurants"),
    sectionUrl(site, "farms"),
    sectionUrl(site, "garden"),
    sectionUrl(site, "meals"),
    sectionUrl(site, "world"),
    sectionUrl(site, "seasons"),
    sectionUrl(site, "pantry"),
    sectionUrl(site, "tags"),
    sectionUrl(site, "recent"),
  ];
  for (const d of dishes) urls.push(entryUrl(site, "dishes", bare(d.id)));
  for (const r of recipes) {
    urls.push(entryUrl(site, "recipes", bare(r.id)));
    urls.push(`${entryUrl(site, "recipes", bare(r.id))}cook/`);
  }
  for (const r of restaurants) urls.push(entryUrl(site, "restaurants", bare(r.id)));
  for (const f of farms) urls.push(entryUrl(site, "farms", bare(f.id)));
  for (const g of garden) urls.push(entryUrl(site, "garden", bare(g.id)));
  for (const m of meals) urls.push(entryUrl(site, "meals", bare(m.id)));

  return new Response(`${urls.join("\n")}\n`, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
