/**
 * /sitemap.json — structured JSON sitemap.
 *
 * Three sitemap formats now live in the repo:
 *   /sitemap-index.xml — canonical XML, generated by @astrojs/sitemap.
 *   /sitemap.txt       — plain text URL list for simpler crawlers.
 *   /sitemap.json      — this file: structured JSON for programmatic consumers
 *                        that want URLs + lastModified hints + section bucket
 *                        without parsing XML.
 *
 * Each URL is grouped by its section (hub / dishes / recipes / etc.) so a
 * consumer can pick a slice without filtering by URL pattern.
 */
import { getCollection } from "astro:content";
import type { APIRoute } from "astro";
import { entryUrl, sectionUrl } from "~/lib/jsonld";
import { bare } from "~/lib/slug";
import { publicOnly } from "~/lib/visibility";

interface SitemapUrl {
  url: string;
  lastModified?: string;
}

export const GET: APIRoute = async ({ site }) => {
  if (!site) {
    throw new Error("Astro.site must be set in astro.config.mjs");
  }

  const [dishes, recipes, farms, restaurants, garden, meals] = await Promise.all([
    getCollection("dishes").then(publicOnly),
    getCollection("recipes").then(publicOnly),
    getCollection("farms").then(publicOnly),
    getCollection("restaurants").then(publicOnly),
    getCollection("garden").then(publicOnly),
    getCollection("meals").then(publicOnly),
  ]);

  const sections = [
    {
      name: "hubs",
      urls: [
        { url: site.toString() },
        { url: new URL("/about/", site).toString() },
        { url: new URL("/lifecycle/", site).toString() },
        { url: new URL("/colophon/", site).toString() },
        { url: new URL("/credits/", site).toString() },
        { url: new URL("/keyboard/", site).toString() },
        { url: sectionUrl(site, "world") },
        { url: sectionUrl(site, "seasons") },
        { url: sectionUrl(site, "pantry") },
        { url: sectionUrl(site, "tags") },
        { url: sectionUrl(site, "recent") },
      ] as SitemapUrl[],
    },
    {
      name: "dishes",
      urls: dishes.map((d) => ({
        url: entryUrl(site, "dishes", bare(d.id)),
        lastModified: d.data.firstMade,
      })),
    },
    {
      name: "recipes",
      urls: recipes.map((r) => {
        const latest = r.data.revisions[r.data.revisions.length - 1];
        return {
          url: entryUrl(site, "recipes", bare(r.id)),
          lastModified: latest?.date,
        };
      }),
    },
    {
      name: "farms",
      urls: farms.map((f) => ({ url: entryUrl(site, "farms", bare(f.id)) })),
    },
    {
      name: "restaurants",
      urls: restaurants.map((r) => ({ url: entryUrl(site, "restaurants", bare(r.id)) })),
    },
    {
      name: "garden",
      urls: garden.map((g) => ({
        url: entryUrl(site, "garden", bare(g.id)),
        lastModified: g.data.harvested ?? g.data.planted,
      })),
    },
    {
      name: "meals",
      urls: meals.map((m) => ({
        url: entryUrl(site, "meals", bare(m.id)),
        lastModified: m.data.date,
      })),
    },
  ];

  const body = {
    version: 1,
    generated: new Date().toISOString(),
    count: sections.reduce((sum, s) => sum + s.urls.length, 0),
    sections,
  };

  return new Response(JSON.stringify(body), {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "public, max-age=600",
      "Access-Control-Allow-Origin": "*",
    },
  });
};
